[package]
name = "kroeg"
version = "0.1.0"
authors = ["Puck Meerburg <puck@puckipedia.com>"]

[features]
default = []
mastodon = ["kroeg-mastodon"]

[dependencies]
kroeg-mastodon = { path = "../mastodon", optional = true }
kroeg-server = { path = "../server" }
hyper = "0.12"
futures = "0.1"
dotenv = "0.9.0"
