[package]
name = "kroeg"
version = "0.1.0"
authors = ["Puck Meerburg <puck@puckipedia.com>"]

[features]
default = ["mastodon", "oauth"]
mastodon = ["kroeg-mastodon"]
oauth = ["kroeg-oauth"]

[dependencies]
kroeg-mastodon = { path = "../mastodon", optional = true }
kroeg-oauth = { path = "../oauth", optional = true }
kroeg-server = { path = "../server" }
hyper = "0.12"
futures = "0.1"
dotenv = "0.9.0"
